terraform {
  required_providers {
    kubernetes = { source = "hashicorp/kubernetes", version = "~> 2.31" }
  }
}

# ---------------------------------------------------------------------------
# Simple single-instance Postgres for dev clusters.
#
# Runs a stock `postgres:<tag>` container (no Bitnami dependency) with:
# - one PVC for $PGDATA
# - a Service at postgres.<namespace>.svc.cluster.local:5432
# - a Secret holding the superuser password
# - an init script that pre-creates per-application databases and roles
#
# NOT production-grade: no HA, no backups, no PITR. For a real cluster use
# CloudNativePG or an external managed PG.
# ---------------------------------------------------------------------------

resource "kubernetes_namespace" "this" {
  count = var.create_namespace ? 1 : 0
  metadata {
    name = var.namespace
    labels = {
      "app.kubernetes.io/part-of" = "agent-platform"
      "agent-platform/component"  = "shared-postgres"
    }
  }
}

locals {
  namespace = var.create_namespace ? kubernetes_namespace.this[0].metadata[0].name : var.namespace

  # Build an init SQL script that creates a role + database for each tenant.
  # Passwords come from var.databases; we pass them as ENV to avoid dumping
  # them into the script (the script references ${DB_xxx_PASSWORD} env vars).
  init_sql = join("\n", concat(
    [
      "-- Auto-generated by terraform module.postgres",
      "",
    ],
    [for db in var.databases : join("\n", [
      "CREATE ROLE ${db.username} LOGIN PASSWORD '${db.password}';",
      "CREATE DATABASE ${db.database} OWNER ${db.username};",
      "GRANT ALL PRIVILEGES ON DATABASE ${db.database} TO ${db.username};",
      "",
    ])],
  ))
}

resource "kubernetes_secret" "superuser" {
  metadata {
    name      = "${var.release_name}-superuser"
    namespace = local.namespace
    labels = {
      "app.kubernetes.io/part-of"  = "agent-platform"
      "app.kubernetes.io/name"     = var.release_name
      "app.kubernetes.io/instance" = var.release_name
    }
  }
  type = "Opaque"
  data = {
    "POSTGRES_PASSWORD" = var.superuser_password
  }
}

resource "kubernetes_config_map" "init" {
  metadata {
    name      = "${var.release_name}-init"
    namespace = local.namespace
    labels = {
      "app.kubernetes.io/part-of"  = "agent-platform"
      "app.kubernetes.io/name"     = var.release_name
      "app.kubernetes.io/instance" = var.release_name
    }
  }
  data = {
    "00-init-databases.sql" = local.init_sql
  }
}

resource "kubernetes_persistent_volume_claim" "data" {
  metadata {
    name      = "${var.release_name}-data"
    namespace = local.namespace
    labels = {
      "app.kubernetes.io/part-of"  = "agent-platform"
      "app.kubernetes.io/name"     = var.release_name
      "app.kubernetes.io/instance" = var.release_name
    }
  }
  spec {
    access_modes = ["ReadWriteOnce"]
    resources {
      requests = {
        storage = var.storage_size
      }
    }
    storage_class_name = var.storage_class == "" ? null : var.storage_class
  }

  # PVC may stay Pending until a pod binds it with WaitForFirstConsumer
  # storageclasses. Don't block apply on it.
  wait_until_bound = false
}

resource "kubernetes_service" "this" {
  metadata {
    name      = var.release_name
    namespace = local.namespace
    labels = {
      "app.kubernetes.io/part-of"  = "agent-platform"
      "app.kubernetes.io/name"     = var.release_name
      "app.kubernetes.io/instance" = var.release_name
    }
  }
  spec {
    type = "ClusterIP"
    selector = {
      "app.kubernetes.io/name"     = var.release_name
      "app.kubernetes.io/instance" = var.release_name
    }
    port {
      name        = "postgres"
      port        = 5432
      target_port = 5432
      protocol    = "TCP"
    }
  }
}

resource "kubernetes_deployment" "this" {
  metadata {
    name      = var.release_name
    namespace = local.namespace
    labels = {
      "app.kubernetes.io/part-of"  = "agent-platform"
      "app.kubernetes.io/name"     = var.release_name
      "app.kubernetes.io/instance" = var.release_name
    }
  }

  spec {
    replicas = 1
    strategy {
      type = "Recreate" # single-PVC, RWO — cannot run two pods at once
    }
    selector {
      match_labels = {
        "app.kubernetes.io/name"     = var.release_name
        "app.kubernetes.io/instance" = var.release_name
      }
    }
    template {
      metadata {
        labels = {
          "app.kubernetes.io/part-of"  = "agent-platform"
          "app.kubernetes.io/name"     = var.release_name
          "app.kubernetes.io/instance" = var.release_name
        }
      }
      spec {
        security_context {
          fs_group     = 999 # postgres UID in the official image
          run_as_user  = 999
          run_as_group = 999
        }
        container {
          name  = "postgres"
          image = "${var.image_repository}:${var.image_tag}"

          env {
            name = "POSTGRES_PASSWORD"
            value_from {
              secret_key_ref {
                name = kubernetes_secret.superuser.metadata[0].name
                key  = "POSTGRES_PASSWORD"
              }
            }
          }
          env {
            name  = "POSTGRES_USER"
            value = var.superuser_username
          }
          env {
            name  = "PGDATA"
            value = "/var/lib/postgresql/data/pgdata"
          }

          port {
            name           = "postgres"
            container_port = 5432
            protocol       = "TCP"
          }

          volume_mount {
            name       = "data"
            mount_path = "/var/lib/postgresql/data"
          }
          volume_mount {
            name       = "init"
            mount_path = "/docker-entrypoint-initdb.d"
            read_only  = true
          }

          readiness_probe {
            exec {
              command = ["sh", "-c", "pg_isready -U ${var.superuser_username} -d postgres"]
            }
            initial_delay_seconds = 10
            period_seconds        = 10
            timeout_seconds       = 5
            failure_threshold     = 6
          }
          liveness_probe {
            exec {
              command = ["sh", "-c", "pg_isready -U ${var.superuser_username} -d postgres"]
            }
            initial_delay_seconds = 60
            period_seconds        = 20
            timeout_seconds       = 5
            failure_threshold     = 6
          }

          resources {
            requests = {
              cpu    = var.resources.requests.cpu
              memory = var.resources.requests.memory
            }
            limits = {
              cpu    = var.resources.limits.cpu
              memory = var.resources.limits.memory
            }
          }
        }

        volume {
          name = "data"
          persistent_volume_claim {
            claim_name = kubernetes_persistent_volume_claim.data.metadata[0].name
          }
        }
        volume {
          name = "init"
          config_map {
            name = kubernetes_config_map.init.metadata[0].name
          }
        }
      }
    }
  }

  depends_on = [
    kubernetes_persistent_volume_claim.data,
    kubernetes_secret.superuser,
    kubernetes_config_map.init,
  ]
}
